version: '2'
services:
    hamburgueria-app:
        image: hamburgueria
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hamburgueria-postgresql:5432/Hamburgueria
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hamburgueria-postgresql:
        extends:
            file: postgresql.yml
            service: hamburgueria-postgresql
