version: '2'
services:
    hamburgueria-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/Hamburgueria/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Hamburgueria
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
